/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Exception.PapelMoedaInvalidaException;
import Exception.SaldoInsuficienteException;
import ticketmaster.PapelMoeda;
import ticketmaster.TicketMaster;

/**
 *
 * @author Carlos Thomaz
 */
public class TicketForm extends javax.swing.JFrame {
     
    private static TicketMaster ticket;
    /**
     * Creates new form TicketForm
     */
    public TicketForm() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saldoAtual = new javax.swing.JTextField();
        saldo = new javax.swing.JLabel();
        emitir = new javax.swing.JButton();
        troco = new javax.swing.JButton();
        valorTXT = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        inserir = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        saldoTXT = new javax.swing.JLabel();

        saldoAtual.setEditable(false);
        saldoAtual.setColumns(20);
        saldoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoAtualActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saldo.setText("Saldo Atual:");

        emitir.setText("Emitir");
        emitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitirActionPerformed(evt);
            }
        });

        troco.setText("Troco");
        troco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocoActionPerformed(evt);
            }
        });

        valorTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTXTActionPerformed(evt);
            }
        });

        valor.setText("Valor:");

        inserir.setText("Inserir");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(valor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(saldo))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(saldoTXT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(status, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(emitir)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 127, Short.MAX_VALUE)
                        .add(troco))
                    .add(valorTXT))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inserir)
                .add(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(saldoTXT))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(valorTXT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(valor)
                    .add(inserir))
                .add(1, 1, 1)
                .add(status)
                .add(3, 3, 3)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emitir)
                    .add(troco))
                .add(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saldoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoAtualActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_saldoAtualActionPerformed

    private void valorTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTXTActionPerformed

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed
        // TODO add your handling code here:         
        int intValor = Integer.parseInt(valorTXT.getText());               
                
        try {            
            Thread.sleep(2000);
            status.setText("Aguarde. Processando...");            
            ticket.inserir(intValor);            
            saldoTXT.setText(Integer.toString(ticket.getSaldo()));
            status.setText("Concluído. Nota aceita.");
        } 
        catch (InterruptedException e) {
        }                                    
        catch (PapelMoedaInvalidaException ex){
            status.setText("Valor inserido não aceito. Favor retirar a nota.");
        }            
        valorTXT.setText("0");
    }//GEN-LAST:event_inserirActionPerformed

    private void emitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emitirActionPerformed
        // TODO add your handling code here: 
        try
        {
            saldoTXT.setText(ticket.imprimir());
        }
        catch(SaldoInsuficienteException ex){
            status.setText("Saldo insuficiente para emitir novo bilhete!");
        }
    }//GEN-LAST:event_emitirActionPerformed

    private void trocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocoActionPerformed
        // TODO add your handling code here:
        try{
        status.setText("Devolver troco de R$"+ticket.getTroco()+",00");
        saldoTXT.setText(Integer.toString(ticket.getSaldo()));
        }
        catch (SaldoInsuficienteException ex){
            status.setText("Saldo está sem crédito para retorno");
        }
    }//GEN-LAST:event_trocoActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        ticket = new TicketMaster(3);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emitir;
    private javax.swing.JButton inserir;
    private javax.swing.JLabel saldo;
    private javax.swing.JTextField saldoAtual;
    private javax.swing.JLabel saldoTXT;
    private javax.swing.JLabel status;
    private javax.swing.JButton troco;
    private javax.swing.JLabel valor;
    private javax.swing.JTextField valorTXT;
    // End of variables declaration//GEN-END:variables
}
